#:import label kivy.uix.label
#:import sla kivy.adapters.listadapter

<MyListItem@SelectableView+BoxLayout>:
	canvas:
		Color:
			rgb: (1, 0, 1)
		Rectangle:
			size: self.size
			pos: self.pos
	Label:
		text: root.word

<MyListView>:
	ListView:
		id: word_list_view
		adapter:
			sla.ListAdapter(
			data=root.word_list,
			cls='MyListItem')
	Button:
		id: add_word_button
		text: 'Add'
		on_press: root.add_word()
